# Generated by Django 4.1.7 on 2023-02-21 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DiseaseID', models.CharField(max_length=120)),
                ('DiseaseName', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DrugID', models.CharField(max_length=120)),
                ('DrugName', models.CharField(max_length=120)),
                ('Diseases', models.ManyToManyField(blank=True, related_name='drugs_for_disease', to='drugdiscovery.disease')),
            ],
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TargetID', models.CharField(max_length=120)),
                ('TargetName', models.CharField(max_length=120)),
                ('Diseases', models.ManyToManyField(blank=True, related_name='targets_for_disease', to='drugdiscovery.disease')),
                ('Drugs', models.ManyToManyField(blank=True, related_name='targets_for_drug', to='drugdiscovery.drug')),
            ],
        ),
    ]
