# Generated by Django 4.1.7 on 2023-02-21 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugdiscovery', '0002_remove_target_diseases'),
    ]

    operations = [
        migrations.AddField(
            model_name='target',
            name='Diseases',
            field=models.ManyToManyField(blank=True, related_name='targets_for_disease', to='drugdiscovery.disease'),
        ),
    ]
