# Generated by Django 4.1.7 on 2023-02-21 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugdiscovery', '0005_target_diseases'),
    ]

    operations = [
        migrations.AddField(
            model_name='drug',
            name='ClinicalStatus',
            field=models.CharField(default='Phase 2', max_length=120),
            preserve_default=False,
        ),
    ]
